spring.application.name=leaderboard-service

server.port=8085

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.database=1

eureka.client.service-url.defaultZone= http://registry-service:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

